development:
  sessions:
    default:
      uri: mongodb://localhost:27017/feira_development
      options:
        consistency: :strong

test:
  sessions:
    default:
      uri: mongodb://localhost:27017/feira_test
      options:
        consistency: :strong

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
